import client from './client'

export const ticketsApi = {
  list:         (cid, params)             => client.get(`/customers/${cid}/tickets`, { params }),
  get:          (cid, id)                => client.get(`/customers/${cid}/tickets/${id}`),
  create:       (cid, data)              => client.post(`/customers/${cid}/tickets`, data),
  update:       (cid, id, data)          => client.put(`/customers/${cid}/tickets/${id}`, data),
  delete:       (cid, id)                => client.delete(`/customers/${cid}/tickets/${id}`),
  addMessage:   (cid, id, body)          => client.post(`/customers/${cid}/tickets/${id}/messages`, { body }),
  addTag:       (cid, id, name)          => client.post(`/customers/${cid}/tickets/${id}/tags`, { name }),
  removeTag:    (cid, id, tagId)         => client.delete(`/customers/${cid}/tickets/${id}/tags/${tagId}`),
  listLinks:    (cid, id)                => client.get(`/customers/${cid}/tickets/${id}/links`),
  addLink:      (cid, id, targetId)      => client.post(`/customers/${cid}/tickets/${id}/links`, { target_ticket_id: targetId }),
  removeLink:   (cid, id, linkId)        => client.delete(`/customers/${cid}/tickets/${id}/links/${linkId}`),
  listCards:    (cid, id)                => client.get(`/customers/${cid}/tickets/${id}/cards`),
  addCardLink:  (cid, id, body)          => client.post(`/customers/${cid}/tickets/${id}/cards`, body),
  removeCardLink:(cid, id, linkId)       => client.delete(`/customers/${cid}/tickets/${id}/cards/${linkId}`),
  getHistory:   (cid, id)                => client.get(`/customers/${cid}/tickets/${id}/history`),
  move:         (cid, id, targetCid)     => client.put(`/customers/${cid}/tickets/${id}/move`, { target_customer_id: targetCid }),
  markSpam:     (cid, id)     => client.post(`/customers/${cid}/tickets/${id}/spam`),
  unmarkSpam:   (cid, id)     => client.delete(`/customers/${cid}/tickets/${id}/spam`),
  inboxList:    (params)      => client.get('/tickets/inbox', { params }),
  inboxCreate:  (data)        => client.post('/tickets/inbox', data),
  inboxGet:     (id)          => client.get(`/tickets/inbox/${id}`),
  inboxUpdate:  (id, data)    => client.put(`/tickets/inbox/${id}`, data),
  inboxDelete:  (id)          => client.delete(`/tickets/inbox/${id}`),
  inboxMessage: (id, body)    => client.post(`/tickets/inbox/${id}/messages`, { body }),
  inboxMarkSpam:   (id)       => client.post(`/tickets/inbox/${id}/spam`),
  inboxUnmarkSpam: (id)       => client.delete(`/tickets/inbox/${id}/spam`),
}
