# -*- coding: utf-8 -*-
# GNU General Public License v2.0+ (see COPYING or https://www.gnu.org/licenses/gpl-2.0.txt)
from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: project
short_description: Manage WarmDesk projects
version_added: "0.1.0"
author:
  - Ton Kersten (@tonk)
description:
  - Create, update, archive, unarchive, star, unstar, or delete WarmDesk projects.
  - Uses project C(name) as the idempotency key; the server-generated C(slug) is
    returned in the result and can be passed to other modules such as
    M(ansilabnl.warmdesk.project_member).
  - Customer and contract associations are looked up by name; the numeric IDs are
    resolved automatically.
notes:
  - The C(slug) field is always generated by the server from the project C(name)
    and cannot be set directly through this module.
  - Updating C(name) changes the project name but does B(not) change the existing
    server-generated slug.
  - Deleting a project is permanent and removes all columns, cards, and members.
  - To manage project membership, use M(ansilabnl.warmdesk.project_member).
extends_documentation_fragment:
  - ansilabnl.warmdesk.connection
options:
  name:
    description:
      - Display name of the project. Used as the idempotency key when searching
        for an existing project.
    type: str
    required: true
  description:
    description:
      - Free-text description of the project. Ignored when C(state=absent).
    type: str
  color:
    description:
      - Hex color code for the project avatar (e.g. C(#3b82f6)). Must include
        the leading C(#). Ignored when C(state=absent).
    type: str
  board_type:
    description:
      - Layout type for the project board.
      - C(kanban) is a free-flowing column board; C(scrum) adds sprint and
        story-point support.
      - Can only be set at creation time; changing it on an existing project is
        not supported by the API and will be silently ignored.
      - Defaults to C(kanban) when omitted.
    type: str
    choices: [kanban, scrum]
  key_prefix:
    description:
      - Card number prefix (e.g. C(EDA) produces card references C(EDA-1),
        C(EDA-2), …). Must be 1–10 uppercase letters or digits.
      - Can only be set at creation time; changing it on an existing project is
        not supported by the API and will be silently ignored.
      - If omitted the server auto-generates a prefix from the project name.
    type: str
  customer:
    description:
      - Name of an existing WarmDesk customer to associate with this project.
        The name is resolved to a numeric C(customer_id) automatically.
      - Required when C(state=present).
    type: str
  contract:
    description:
      - Name of an existing contract belonging to the customer specified in
        C(customer). Requires C(customer) to also be set.
        The name is resolved to a numeric C(contract_id) automatically.
      - Pass an empty string or omit the parameter to clear the association.
    type: str
  is_archived:
    description:
      - Whether the project should be archived. Archived projects are hidden
        from most list views but are not deleted.
      - Defaults to C(false) on creation; if omitted on update the current
        value is preserved.
    type: bool
  is_closed:
    description:
      - Whether the project board should be closed. Closed projects are hidden
        from sidebar lists and excluded from I(GET /api/v1/projects) by default.
      - Can be set to C(true) to close or C(false) to reopen a project board.
        Only project owners, admins, and global admins can close/reopen a
        project.
      - Defaults to C(false) on creation; if omitted on update the current
        value is preserved.
    type: bool
  starred:
    description:
      - Whether the authenticated user should star this project.
      - C(true) calls C(POST /projects/:slug/star); C(false) calls
        C(DELETE /projects/:slug/star).
      - Has no effect when C(state=absent).
    type: bool
  state:
    description:
      - C(present) ensures the project exists and matches the given attributes.
      - C(absent) deletes the project if it exists.
    type: str
    choices: [present, absent]
    default: present
'''

EXAMPLES = r'''
- name: Create a project
  ansilabnl.warmdesk.project:
    warmdesk_url: https://desk.example.com
    warmdesk_token: "{{ vault_wd_token }}"
    name: Infrastructure
    customer: Acme Corp
    state: present

- name: Create a fully specified project
  ansilabnl.warmdesk.project:
    warmdesk_url: https://desk.example.com
    warmdesk_api_key: "{{ vault_wd_api_key }}"
    name: Edge Data Analytics
    description: "Analytics platform cards and tasks"
    color: "#3b82f6"
    key_prefix: EDA
    customer: Acme Corp
    contract: "Support 2026"
    is_archived: false
    starred: true
    state: present
  register: project_result

- name: Use the returned slug in a downstream task
  ansilabnl.warmdesk.project_member:
    warmdesk_url: https://desk.example.com
    warmdesk_token: "{{ vault_wd_token }}"
    project: "{{ project_result.project.slug }}"
    username: jdoe
    role: member
    state: present

- name: Archive a project
  ansilabnl.warmdesk.project:
    warmdesk_url: https://desk.example.com
    warmdesk_token: "{{ vault_wd_token }}"
    name: Edge Data Analytics
    is_archived: true
    state: present

- name: Unarchive a project
  ansilabnl.warmdesk.project:
    warmdesk_url: https://desk.example.com
    warmdesk_token: "{{ vault_wd_token }}"
    name: Edge Data Analytics
    customer: Acme Corp
    is_archived: false
    state: present

- name: Create a scrum project
  ansilabnl.warmdesk.project:
    warmdesk_url: https://desk.example.com
    warmdesk_token: "{{ vault_wd_token }}"
    name: Sprint Board
    customer: Acme Corp
    board_type: scrum
    state: present

- name: Close a project board
  ansilabnl.warmdesk.project:
    warmdesk_url: https://desk.example.com
    warmdesk_token: "{{ vault_wd_token }}"
    name: Edge Data Analytics
    customer: Acme Corp
    is_closed: true
    state: present

- name: Reopen a project board
  ansilabnl.warmdesk.project:
    warmdesk_url: https://desk.example.com
    warmdesk_token: "{{ vault_wd_token }}"
    name: Edge Data Analytics
    customer: Acme Corp
    is_closed: false
    state: present

- name: Ensure a project does not exist
  ansilabnl.warmdesk.project:
    warmdesk_url: https://desk.example.com
    warmdesk_token: "{{ vault_wd_token }}"
    name: Old Project
    state: absent
'''

RETURN = r'''
changed:
  description: Whether the module made any changes.
  type: bool
  returned: always
  sample: true
project:
  description:
    - The current state of the project after the module ran.
    - C(null) when C(state=absent) and the project did not exist or was deleted.
  type: dict
  returned: always
  contains:
    id:
      description: Numeric project ID.
      type: int
      sample: 42
    name:
      description: Project display name.
      type: str
      sample: Edge Data Analytics
    slug:
      description: URL-safe identifier generated by the server from the project name.
      type: str
      sample: edge-data-analytics
    description:
      description: Project description.
      type: str
      sample: "Analytics platform cards and tasks"
    color:
      description: Hex colour code.
      type: str
      sample: "#3b82f6"
    board_type:
      description: Board layout type — C(kanban) or C(scrum).
      type: str
      sample: kanban
    key_prefix:
      description: Card reference prefix.
      type: str
      sample: EDA
    is_archived:
      description: Whether the project is archived.
      type: bool
      sample: false
    is_closed:
      description: Whether the project board is closed.
      type: bool
      sample: false
    position:
      description: Display ordering position.
      type: int
      sample: 0
    customer_id:
      description: Numeric ID of the associated customer, or null.
      type: int
      sample: 7
    contract_id:
      description: Numeric ID of the associated contract, or null.
      type: int
      sample: 3
    created_by_id:
      description: Numeric ID of the user who created the project.
      type: int
      sample: 1
    created_at:
      description: ISO-8601 creation timestamp.
      type: str
      sample: "2026-01-15T10:30:00Z"
    updated_at:
      description: ISO-8601 last-update timestamp.
      type: str
      sample: "2026-04-01T08:00:00Z"
    open_card_count:
      description: Number of open (non-closed) cards in the project.
      type: int
      sample: 14
'''

from ansible.module_utils.basic import AnsibleModule

from ansible_collections.ansilabnl.warmdesk.plugins.module_utils.warmdesk_api import (
    WarmDeskAPIError,
    WarmDeskClient,
    warmdesk_argument_spec,
)
from ansible_collections.ansilabnl.warmdesk.plugins.module_utils.warmdesk_resolve import (
    resolve_customer_id,
    resolve_contract_id,
)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _find_project_by_name(client, name):
    """Return the ProjectListItem dict whose name equals *name*, or None."""
    projects = client.get('/projects')
    for p in projects:
        if p['name'] == name:
            return p
    return None


def _is_starred(client, slug):
    """Return True if the calling user has starred the project."""
    starred = client.get('/projects/starred')
    for p in starred:
        if p['slug'] == slug:
            return True
    return False


def _build_update_body(params, customer_id, contract_id, existing):
    """Build the PUT body, only including fields the caller wants to change.

    The server always overwrites customer_id/contract_id (even with null) so
    we need to send the resolved values (or None to clear).
    """
    body = {}

    if params['name'] is not None:
        body['name'] = params['name']
    if params['description'] is not None:
        body['description'] = params['description']
    if params['color'] is not None:
        body['color'] = params['color']
    if params['is_archived'] is not None:
        body['is_archived'] = params['is_archived']
    if params['is_closed'] is not None:
        body['is_closed'] = params['is_closed']

    # customer/contract: None means "caller did not supply the param" (preserve
    # existing value); an explicit empty string means "clear the association".
    # After resolution: customer_id / contract_id are either an int, None (clear),
    # or SENTINEL (not supplied).
    body['customer_id'] = customer_id
    body['contract_id'] = contract_id

    return body


def _needs_update(existing, desired_body):
    """Return True if any field in desired_body differs from existing."""
    field_map = {
        'name': 'name',
        'description': 'description',
        'color': 'color',
        'is_archived': 'is_archived',
        'is_closed': 'is_closed',
        'customer_id': 'customer_id',
        'contract_id': 'contract_id',
    }
    for body_key, proj_key in field_map.items():
        if body_key not in desired_body:
            continue
        if desired_body[body_key] != existing.get(proj_key):
            return True
    return False


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def run_module():
    argument_spec = warmdesk_argument_spec()
    argument_spec.update(
        name=dict(type='str', required=True),
        description=dict(type='str'),
        color=dict(type='str'),
        board_type=dict(type='str', choices=['kanban', 'scrum']),
        key_prefix=dict(type='str'),
        customer=dict(type='str'),
        contract=dict(type='str'),
        is_archived=dict(type='bool'),
        is_closed=dict(type='bool'),
        starred=dict(type='bool'),
        state=dict(type='str', default='present', choices=['present', 'absent']),
    )

    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True,
        required_if=[('state', 'present', ['customer'])],
    )

    params = module.params
    state = params['state']
    name = params['name']

    try:
        client = WarmDeskClient.from_module(module)

        # ------------------------------------------------------------------
        # Resolve customer / contract names → IDs
        # ------------------------------------------------------------------
        # SENTINEL means the param was not supplied; None means "clear".
        _SENTINEL = object()

        # customer param: None if not given, '' to clear, 'Name' to resolve
        customer_param = params.get('customer')
        contract_param = params.get('contract')

        customer_id = _SENTINEL
        contract_id = _SENTINEL

        if customer_param:
            customer_id = resolve_customer_id(client, customer_param)
            if contract_param is not None:
                if contract_param == '':
                    contract_id = None
                else:
                    contract_id = resolve_contract_id(client, customer_id, contract_param)

        # ------------------------------------------------------------------
        # Look up existing project
        # ------------------------------------------------------------------
        existing = _find_project_by_name(client, name)

        # ------------------------------------------------------------------
        # state=absent
        # ------------------------------------------------------------------
        if state == 'absent':
            if existing is None:
                module.exit_json(changed=False, project=None)
            if not module.check_mode:
                client.delete('/projects/%s' % existing['slug'])
            module.exit_json(changed=True, project=None)

        # ------------------------------------------------------------------
        # state=present — Create
        # ------------------------------------------------------------------
        if existing is None:
            create_body = {'name': name}
            if params['description'] is not None:
                create_body['description'] = params['description']
            if params['color'] is not None:
                create_body['color'] = params['color']
            if params['board_type'] is not None:
                create_body['board_type'] = params['board_type']
            if params['key_prefix'] is not None:
                create_body['key_prefix'] = params['key_prefix']
            if customer_id is not _SENTINEL:
                create_body['customer_id'] = customer_id
            if contract_id is not _SENTINEL:
                create_body['contract_id'] = contract_id

            if module.check_mode:
                # Return a synthetic result so downstream tasks can see the
                # anticipated shape, but without a real slug.
                module.exit_json(
                    changed=True,
                    project=dict(create_body, slug=None, id=None),
                )

            project = client.post('/projects', create_body)

            # Handle starring after creation
            if params['starred'] is True:
                client.post('/projects/%s/star' % project['slug'])
            elif params['starred'] is False:
                client.delete('/projects/%s/star' % project['slug'])

            module.exit_json(changed=True, project=project)

        # ------------------------------------------------------------------
        # state=present — Update
        # ------------------------------------------------------------------
        slug = existing['slug']

        # Resolve sentinel to existing value so diff is correct
        resolved_customer_id = (
            existing.get('customer_id') if customer_id is _SENTINEL else customer_id
        )
        resolved_contract_id = (
            existing.get('contract_id') if contract_id is _SENTINEL else contract_id
        )

        update_body = {}
        if params['name'] is not None:
            update_body['name'] = params['name']
        if params['description'] is not None:
            update_body['description'] = params['description']
        if params['color'] is not None:
            update_body['color'] = params['color']
        if params['is_archived'] is not None:
            update_body['is_archived'] = params['is_archived']
        if params['is_closed'] is not None:
            update_body['is_closed'] = params['is_closed']
        # Always include customer/contract so the server can clear them
        update_body['customer_id'] = resolved_customer_id
        update_body['contract_id'] = resolved_contract_id

        project_changed = _needs_update(existing, update_body)

        # Determine star change (only if caller specified)
        star_changed = False
        if params['starred'] is not None:
            current_starred = _is_starred(client, slug)
            star_changed = (params['starred'] != current_starred)

        changed = project_changed or star_changed

        if module.check_mode:
            result_project = dict(existing)
            result_project.update(update_body)
            module.exit_json(changed=changed, project=result_project)

        if project_changed:
            project = client.put('/projects/%s' % slug, update_body)
        else:
            # Re-fetch to ensure return value is fresh
            project = client.get('/projects/%s' % slug)

        if star_changed:
            if params['starred']:
                client.post('/projects/%s/star' % slug)
            else:
                client.delete('/projects/%s/star' % slug)

        module.exit_json(changed=changed, project=project)

    except WarmDeskAPIError as exc:
        module.fail_json(
            msg='WarmDesk API error (HTTP %s): %s' % (exc.status, exc.message)
        )


def main():
    run_module()


if __name__ == '__main__':
    main()
